CONCEPTS = "concepts"
CONCEPTS_DATA_VERSION = "concepts_data_version"
ANNOTATION_HISTORY = "annotation_history"
AVAILABLE_CONFIG = "available_config"
SELECTED_PLATFORM = "selected_platform"
SELECTED_MODEL = "selected_model"
SELECTED_CONCEPT = "selected_concept"
EDITING_CONCEPT_INDEX = "editing_concept_index"
REUSE_TEXT = "reuse_text"
DEBUG_NOTICE_ACK = "debug_notice_ack"
DEBUG_NOTICE_STARTED_AT = "debug_notice_started_at"

# Widget keys
PLATFORM_SELECTOR = "platform_selector"
MODEL_SELECTOR = "model_selector"
