services:
  rosetta:
    image: rosetta-app:latest
    container_name: rosetta-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    restart: unless-stopped
    environment:
      - ROSETTA_RUNTIME_DIR=/opt/rosetta/runtime
    volumes:
      - /opt/streamlit/rosetta:/app:ro
      - /opt/rosetta/runtime:/opt/rosetta/runtime
